################################################################
## Packages / Batteries
################################################################
input_label:
  nicole_battery:
  justin_battery:
  nicole_wifi:
  justin_wifi:

group:
  Phone Batteries:
    entities:
      - input_label.justin_battery
      - input_label.nicole_battery
  Phone WiFi:
    entities:
      - input_label.justin_wifi
      - input_label.nicole_wifi
  Batteries:
    name: Battery Levels
    entities:
     - sensor.kitchen_nest_protect_battery_health
     - sensor.battery_finn_sensor_dynamic
     - sensor.battery_finn_switch_dynamic
     - sensor.battery_livingroom_sensor_dynamic
     - sensor.battery_diningroom_sensor_dynamic
     - sensor.battery_hallway_switch_dynamic
     - sensor.justin_battery
     - sensor.nicole_battery

automation:
  - alias: Update Phone Battery Levels
    initial_state: true
    trigger:
      platform: mqtt
      topic: "owntracks/+/+"
    action:
      - service: input_label.set_value
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_wifi"
          value: "{{ 'Yes' if trigger.payload_json.conn == 'w' else 'No' }}"
      - service: input_label.set_icon
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_wifi"
          value: "{{ 'mdi:wifi' if trigger.payload_json.conn == 'w' else 'mdi:wifi-off' }}"
      - service: input_label.set_name
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_wifi"
          value: "{{trigger.topic.split('/')[-1] | title }}'s phone wifi enabled?"

      - service: input_label.set_value
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_battery"
          value: '{{ trigger.payload_json.batt | int }}'
      - service: input_label.set_name
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_battery"
          value: "{{trigger.topic.split('/')[-1] | title }}'s Battery"
      - service: input_label.set_icon
        data_template:
          entity_id: "input_label.{{trigger.topic.split('/')[-1]}}_battery"
          value: >
              {% set battery_level = trigger.payload_json.batt | int %}
              {% set battery_round = (battery_level / 10)|int * 10 %}
              {% if trigger.payload_json.charging == 1 %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}

  - alias: 'Battery Alert'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '10:00:00'
      - platform: time
        at: '18:00:00'
    condition:
      condition: template
      value_template: "{% if states('sensor.battery_low') == 'Low Battery' %}false{%else%}true{% endif %}"
    action:
      - service: persistent_notification.create
        data_template:
          title: Low Battery
          message: "{{ states('sensor.battery_low') }}"
          notification_id: low-battery-alert
      - service: notify.html5
        data_template:
          target: justin
          message:  "Low battery levels: {{ states('sensor.battery_low') }}"

sensor:
###### DUMMY SENSOR FOR NEST PROTECT TO NOTIFY
  - platform: template
    sensors:
      battery_nest_protect_kitchen:
        friendly_name: 'Kitchen Nest Protect'
        value_template: >-
          {% set battery = states.sensor.kitchen_nest_protect_battery_health.state %}
          {% if battery == 'Ok' %}100{% else %}0{% endif %}
###### PHILIPS HUE MOTION SENSOR AND SWITCHES
  - platform: rest
    resource: !secret finn_room_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'batteryraw_finn_sensor'
  - platform: template
    sensors:
      battery_finn_sensor_dynamic:
        friendly_name: 'Findlays Room Sensor'
        value_template: "{{ states.sensor.batteryraw_finn_sensor.state }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states.sensor.batteryraw_finn_sensor.state|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          {% endif %}

  - platform: rest
    resource: !secret finn_room_switch_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'batteryraw_finn_switch'
  - platform: template
    sensors:
      battery_finn_switch_dynamic:
        friendly_name: 'Findlays Room Switch'
        value_template: "{{ states.sensor.batteryraw_finn_switch.state }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states.sensor.batteryraw_finn_switch.state|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          {% endif %}

  - platform: rest
    resource: !secret livingroom_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'batteryraw_livingroom_sensor'
  - platform: template
    sensors:
      battery_livingroom_sensor_dynamic:
        friendly_name: 'Living Room Sensor'
        value_template: "{{ states.sensor.batteryraw_livingroom_sensor.state }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states.sensor.batteryraw_livingroom_sensor.state|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          {% endif %}

  - platform: rest
    resource: !secret livingroom_switch_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'batteryraw_hallway_switch'
  - platform: template
    sensors:
      battery_hallway_switch_dynamic:
        friendly_name: 'Hallway Switch'
        value_template: "{{ states.sensor.batteryraw_hallway_switch.state }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states.sensor.batteryraw_hallway_switch.state|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          {% endif %}

  - platform: rest
    resource: !secret dining_room_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'batteryraw_diningroom_sensor'
  - platform: template
    sensors:
      battery_diningroom_sensor_dynamic:
        friendly_name: 'Dining Room Sensor'
        value_template: "{{ states.sensor.batteryraw_diningroom_sensor.state }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states.sensor.batteryraw_diningroom_sensor.state|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          {% endif %}

  ##### Owntracks Battery Tracker for Cell Phones
  - platform: mqtt
    state_topic: "owntracks/justin/justin"
    name: "Justin's Battery State"
    value_template: >
      {% if value_json.charging == 1 %}
        Charging
      {% else %}
        Not Charging
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/justin/justin"
    name: "Justin's Battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"

  - platform: mqtt
    state_topic: "owntracks/nicole/nicole"
    name: "Nicole's Battery State"
    value_template: >
      {% if value_json.charging == 1 %}
        Charging
      {% else %}
        Not Charging
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/nicole/nicole"
    name: "Nicole's Battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"

  - platform: template
    sensors:
      justin_battery:
        friendly_name: Justin's Phone Battery
        unit_of_measurement: '%'
        value_template: "{{ states('sensor.justins_battery')|int(-1) }}"
        icon_template: >-
          {% if states('sensor.justin_battery') != "unknown" %}
            {% set battery_level = states('sensor.justins_battery')|int (-1)%}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if states.sensor.justins_battery_state.state | lower == "charging" %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% else %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}
      nicole_battery:
        friendly_name: Nicole's Phone Battery
        unit_of_measurement: '%'
        value_template: "{{ states('sensor.nicoles_battery')|int(-1) }}"
        icon_template: >-
          {% if states('sensor.nicole_battery') != "unknown" %}
            {% set battery_level = states('sensor.nicoles_battery')|int (-1)%}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if states.sensor.nicoles_battery_state.state | lower == "charging" %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% else %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}

###### LIST OF LOW BATTERIES ( sensor.battery_ )
  - platform: template
    sensors:
      battery_low:
        friendly_name: 'Low Battery'
        icon_template: mdi:battery-alert
        value_template: >-
          {%- for item in states.sensor if ((item.entity_id[0:15] == 'sensor.battery_' and item.state |int < 10)) -%}
            {{item.name}}
          {%- if not loop.last -%}
          {{', '}}
            {%- endif -%}
          {%- endfor -%}
