################################################################
## Packages / Night Light
################################################################
homeassistant:
  customize:
    scene.nightlight:
      friendly_name: 'Night Light'
      icon: mdi:brightness-2

automation:
  - alias: 'Night Light'
    trigger:
      - platform: state
        entity_id: sensor.living_room_motion, sensor.dining_room_motion
        to: 'True'
    condition:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      - condition: state
        entity_id: 'input_boolean.vacation'
        state: 'off'
      - condition: state
        entity_id: 'input_boolean.away'
        state: 'off'
      - condition: time
        after: '11:59:00'
    action:
      - service: script.turn_off
        data:
          entity_id: script.nightlight
      - service: script.turn_on
        data:
          entity_id: script.nightlight

script:
  nightlight:
    sequence:
     - service: light.turn_on
       data:
         entity_id:
           light.hue_color_lamp_1:
           light.hue_color_lamp_3:
           light.kitchen_sink:
             brightness: 1
             color_temp: 450
     - delay:
          minutes: 8
     - service: light.turn_off
       data:
         entity_id:
           light.hue_color_lamp_1:
           light.hue_color_lamp_3:
           light.kitchen_sink:
             state: off
