################################################################
## Packages / Pi-Hole
## @norien - https://github.com/Norien/Home-Assistant-Config
## #!secret_example
#pi_hole_url: http://192.168.0.55/admin/api.php
#Authorization & Token required (see WEBPASSWORD in /etc/pihole/setupVars.conf)
#pi_hole_switch_on: /usr/bin/curl -k "localhost/admin/api.php?enable&auth=webkey"
#pi_hole_switch_off: /usr/bin/curl -k "localhost/admin/api.php?disable=600&auth=webkey"
# the .SH file I am using is here
#https://github.com/Norien/Home-Assistant-Config/blob/master/shell/pihole.sh
################################################################
homeassistant:
  customize:
    switch.pihole:
      friendly_name: Pi-Hole
      entity_picture: /local/custom_icons/pihole.png

    sensor.ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb

    sensor.ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb

    sensor.dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    sensor.unique_domains:
      friendly_name: Unique Domains
      icon: mdi:approval

    sensor.queries_forwarded:
      friendly_name: Queries Forwarded
      icon: mdi:arrange-send-backward

    sensor.queries_cached:
      friendly_name: Queries Cached
      icon: mdi:animation

    script.ad_blocker:
      friendly_name: Ad Blocker
      emulated_hue: true

    script.pihole_off:
      friendly_name: Turn Pi-Hole Off
      icon: mdi:do-not-disturb

    script.pihole_on:
      friendly_name: Turn Pi-Hole On
      icon: mdi:power

    script.pihole_update:
      friendly_name: Update Pi-Hole
      icon: mdi:package-variant

    sensor.pihole_dns:
      friendly_name: DNS Service

    sensor.pihole_blocking:
      friendly_name: Ad Blocking

    sensor.pi_hole_version:
      friendly_name: Version

group:
  Ads Blocked:
    entities:
      - switch.pihole
      - sensor.ads_blocked_today
      - sensor.ads_percentage_today
      - sensor.dns_queries_today
      - sensor.domains_being_blocked
      - sensor.ads_blocked_today
      - sensor.unique_domains
      - sensor.queries_forwarded
      - sensor.queries_cached
      - sensor.pihole_dns
      - sensor.pihole_blocking
      - sensor.pi_hole_version
      - script.pihole_update

###############################################################################
#  Sensors
###############################################################################
sensor:
  - platform: rest
    name: dns_queries_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.dns_queries_today }}'

  - platform: rest
    name: domains_being_blocked
    resource: !secret pi_hole_url
    value_template: '{{ value_json.domains_being_blocked }}'

  - platform: rest
    name: ads_blocked_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.ads_blocked_today }}'

  - platform: rest
    name: ads_percentage_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.ads_percentage_today | int }}'

  - platform: rest
    name: unique_domains
    resource: !secret pi_hole_url
    value_template: '{{ value_json.unique_domains }}'

  - platform: rest
    name: queries_forwarded
    resource: !secret pi_hole_url
    value_template: '{{ value_json.queries_forwarded }}'

  - platform: rest
    name: queries_cached
    resource: !secret pi_hole_url
    value_template: '{{ value_json.queries_cached }}'

######Custom Version sensor
  - platform: command_line
    command: "pihole -v -p -c"
    name: 'pihole_version_current'
    value_template: '{{ value[28:] }}'
    scan_interval: 86400

  - platform: command_line
    command: "pihole -v -p -l"
    name: 'pihole_version_latest'
    value_template: '{{ value[27:] }}'
    scan_interval: 86400

  - platform: template
    sensors:
      pi_hole_version:
        value_template: "{%- if states.sensor.pihole_version_current.state == states.sensor.pihole_version_latest.state -%}{{states.sensor.pihole_version_current.state}} {% else %}{{states.sensor.pihole_version_latest.state}} Available{% endif%}"
        icon_template: >-
          {% if states.sensor.pihole_version_current.state == states.sensor.pihole_version_latest.state %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}
###### I had to provide access in sudoers file for this script to run.
  - platform: command_line
    command: 'pihole status'
    name: 'pihole_status_raw'
    scan_interval: 60

  - platform: template
    sensors:
      pihole_dns:
        value_template: "{{states.sensor.pihole_status_raw.state.split('[✓]')[1][1:-3]}}"
        icon_template: >-
          {%- if states.sensor.pihole_status_raw.state.split('[✓]')[1][1:-3] == 'DNS service is running' -%}
            mdi:checkbox-marked
          {%- else -%}
            mdi:checkbox-blank-outline
          {%- endif -%}

  - platform: template
    sensors:
      pihole_blocking:
        value_template: "{{states.sensor.pihole_status_raw.state.split('[✓]')[2][1:]}}"
        icon_template: >-
          {% if states.sensor.pihole_blocking.state == 'Pi-hole blocking is Enabled' %}
            mdi:checkbox-blank-outline
          {% else %}
            mdi:checkbox-marked
          {% endif %}

  - platform: template
    sensors:
      pihole_status:
        value_template: >-
          {% if states.sensor.pihole_blocking.state == 'Pi-hole blocking is Enabled' %}
            True
          {% else %}
            False
          {% endif %}
###############################################################################
#  Switch
###############################################################################
switch:
  - platform: template
    switches:
      pihole:
        value_template: '{{ states.sensor.pihole_status.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.pihole_on
        turn_off:
          service: script.turn_on
          entity_id: script.pihole_off
###############################################################################
#  Scripts
###############################################################################
script:
  # this script is just for alexa to toggle on/off
  ad_blocker:
    sequence:
      - service: switch.toggle
        entity_id: switch.pihole
  pihole_on:
    sequence:
       - service: shell_command.pihole_on
  pihole_off:
    sequence:
       - service: shell_command.pihole_off
  pihole_update:
    sequence:
       - service: shell_command.pihole_update
###############################################################################
#  Shell Command
###############################################################################
shell_command:
  pihole_on: !secret pi_hole_switch_on
  pihole_off: !secret pi_hole_switch_off
  pihole_update: "pihole -up"
