################################################################
## Packages / Master Bedroom
################################################################
homeassistant:
  customize:
    switch.white_noise:
      emulated_hue: true
      friendly_name: 'White Noise'
      icon: mdi:snowflake
    media_player.kodi_bedroom:
      friendly_name: Bedroom KODI
    media_player.kodi_bedroom_pi:
      friendly_name: Bedroom KODI PI
    switch.bedroom_fan:
      emulated_hue: true
      icon: mdi:fan
      friendly_name: Bedroom Fan
    switch.bedroom_lamps_:
      emulated_hue: true
      icon: mdi:lamp
      friendly_name: Bedroom Lamp
    switch.led_strip:
      emulated_hue: true
      icon: mdi:lamp
      friendly_name: Bedroom Headboard      
    #Bedroom computer Switch
    switch.bedroom_media:
      emulated_hue: true
      icon: mdi:monitor
      friendly_name: Bedroom Media

###### STATE CARD
group:
  bedroom:
    name: Master Bedroom
    control: hidden
    entities:
     - switch.bedroom_media
     - switch.bedroom_lamps_
     - switch.bedroom_fan
     - switch.bedroom_tv
     - switch.white_noise
     - input_select.white_noise
     - switch.led_strip
     - input_select.led_scene
     - input_select.led_color
     - binary_sensor.flic_80e4da71b68e
     - switch.bedroom_fan_a
     - switch.bedroom_fan_b

binary_sensor:
  - platform: flic
    host: 192.168.1.92

sensor:
  - platform: template
    sensors:
      white_noise:
        value_template: "{% if is_state('media_player.kodi_bedroom_pi', 'playing') %}on{% else %}Off{% endif %}"

switch:
###### Switch for White Noise
  - platform: template
    switches:
      white_noise:
        value_template: '{{ states.sensor.white_noise.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.white_noise
        turn_off:
          service: media_player.media_Stop
          entity_id: media_player.kodi_bedroom_pi
###### SONOFF DUAL 1
  - platform: mqtt
    name: "Bedroom Fan A"
    state_topic: "stat/sonoff_dual/POWER1"
    command_topic: "cmnd/sonoff_dual/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
###### SONOFF DUAL 2
  - platform: mqtt
    name: "Bedroom Fan B"
    state_topic: "stat/sonoff_dual/POWER2"
    command_topic: "cmnd/sonoff_dual/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
###### BEDROOM PC SWITCH with TV
  - platform: wake_on_lan
    mac_address: !secret kodi_bedroom_mac
    name: "bedroom_pc"
    host: !secret kodi_bedroom_ip
    broadcast_address: 255.255.255.255
    turn_off:
      service: script.bedroom_kodi_off

  - platform: template
    switches:
      bedroom_media:
        value_template: '{{ states.switch.bedroom_pc.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.bedroom_media_on
        turn_off:
          service: script.turn_on
          entity_id: script.bedroom_media_off

script:
  bedroom_media_on:
    sequence:
      - service: switch.turn_on
        entity_id: switch.bedroom_tv
      - delay: '00:00:10'
      - service: switch.turn_on
        entity_id: switch.bedroom_pc
      - service: shell_command.bedroom_tv_cec

  bedroom_media_off:
    sequence:
      - service: switch.turn_off
        entity_id: switch.bedroom_tv
      - service: switch.turn_off
        entity_id: switch.bedroom_pc

  bedroom_kodi_off:
    sequence:
      - service: shell_command.curl
        data_template:
          url: !secret kodi_bedroom_json
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            method: "System.Hibernate"

  white_noise:
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.kodi_bedroom_pi
          media_content_id: "http://192.168.1.250:8123/local/white_noise/blizzard.mp3"
          media_content_type: "audio/mp3"

automation:
  - alias: 'white_noise'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.white_noise
    action:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kodi_bedroom_pi
          media_content_id: >
            {% if is_state('input_select.white_noise', 'Blizzard') %} http://192.168.1.250:8123/local/white_noise/blizzard.mp3
            {% elif is_state('input_select.white_noise', 'Blizzard2') %} http://192.168.1.250:8123/local/white_noise/blizzard2.mp3
            {% elif is_state('input_select.white_noise', 'Rain') %} http://192.168.1.250:8123/local/white_noise/rain.mp3
            {% endif %}
          media_content_type: 'audio/mp3'

  - alias: 'bedroom flic single'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da71b68e
        click_type: single
    action:
      service: switch.toggle
      entity_id: switch.bedroom_fan

  - alias: 'bedroom flic double'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da71b68e
        click_type: double
    action:
      - service: switch.toggle
        entity_id: switch.bedroom_lamps_
      - service: switch.toggle
        entity_id: switch.led_strip

  - alias: 'bedroom flic hold'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: flic_80e4da71b68e
        click_type: hold
    action:
      - service: switch.turn_off
        entity_id: switch.bedroom_tv
      - service: switch.turn_off
        entity_id: switch.bedroom_lamps_
      - service: switch.turn_off
        entity_id: switch.led_strip
      - service: switch.turn_on
        entity_id: switch.bedroom_fan
      - service: switch.turn_on
        entity_id: switch.white_noise

shell_command:
  bedroom_tv_cec: 'bash /home/homeassistant/.homeassistant/shell/cec.sh'

input_select:
  white_noise:
    name: White Noise
    options:
      - Blizzard
      - Blizzard2
      - Rain
    initial: "Blizzard"
    icon: mdi:bookmark-music
